### ISSUE TITLE
New release tag?

### ISSUE THREAD

**Issue by cshields** [mozilla/django-dnt#7]
@jwhitlock 

Assuming all was well with django 2-3 in dd80b6e, could this be tagged so a release hits pypi?

thanks!

**Comment by jwhitlock** [comment]
Yes, this looks fine for a release. However, the last Django it covers is 2.2, so Django 3.x is untested.

I haven't been on a project that uses this package for about a year, so I should look for a maintainer as well. It may make sense to walk the new maintainer(s) through a release, which would further delay tagging this.

@cshields, what is your timeline for needing a new release? Hours? Days? Weeks?

**Comment by cshields** [comment]
> @cshields, what is your timeline for needing a new release? Hours? Days? Weeks?

Its for a personal project so I can't press for any kind of priority here.. And its 2.2, so "tag it now" and handle 3 later?  :)

**Comment by jwhitlock** [comment]
A tag for 2.2 makes sense to me, since the next release should drop 1.11 and earlier. I like having some overlap so you can avoid big bang updates of Django, Python, and libraries.

**Comment by jwhitlock** [comment]
[version 1.0](https://pypi.org/project/django-dnt/1.0/) is released to PyPy. It doesn't officially say 3.x is supported, but the [TravisCI build](https://travis-ci.org/github/mozilla/django-dnt/jobs/717310893) with Python 3.7 and Django master works, so there is a good chance it will work with no changes.
